### PR TITLE
chore: fix permissions

### PR DESCRIPTION
**Pull request by ryanleecode**
## **User description**
Updates the nextjs permissions to use the "remotion-executionrole-policy`: https://www.remotion.dev/docs/lambda/without-iam/#1-create-role-policy. This means we don't need to pass in AWS admin keys anymore.

___

## **Type**
enhancement

___

## **Description**
- Imported `pulumi` to manage AWS resources more efficiently.
- Enhanced security by removing the need for AWS admin keys in environment variables.
- Implemented a new permissions model using the remotion execution role policy, as recommended in the Remotion documentation.
- Defined granular permissions for AWS services like Service Quotas, IAM, S3, Lambda, and Logs to ensure least privilege access.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>sst.config.ts</strong><dd><code>Enhance Security by Using Remotion Execution Role Policy and Removing </code><br><code>AWS Admin Keys</code></dd></summary>
<hr>
      
sst.config.ts

<li>Imported <code>pulumi</code> from <code>@pulumi/pulumi</code>.<br> <li> Removed AWS admin keys from environment variables.<br> <li> Added a transformation function to combine linked permissions with the <br>remotion execution role policy.<br> <li> Defined specific actions and resources for various AWS services <br>including Service Quotas, IAM, S3, Lambda, and Logs.<br>

</details>
    

  </td>
  <td><a href="https://github.com/karelnagel/pulumi-remotion-lambda/pull/2/files#diff-6ae5efcb80db51f4b137515e1674caaf950405317e84e2961cf38f9d3a1804b9">+76/-3</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by karelnagel** [comment]
lol, I didn't know that codium PR agent worked on all of my repos now 😅

This is great!
I think we should export these permissions from the src/index.ts file, then it could be re-used in other projects and sst.config.ts would be cleaner. Also, there is `permissions` field in `new Astro({})` and I'm wondering if it would still work if we send the permissions there instead of `transform.server.permissions`? 

I messed up my SST deployment so I'm trying to solve that and then I can test.

**Comment by ryanleecode** [comment]
1. definately
2. check https://ion.sst.dev/docs/component/aws/astro/#transform should be
the same across astro/remix/next
3. that bot is insanely cool

**Comment by ryanleecode** [comment]
actually no it shouldnt work if we just put it inside the package. it needs
to go on astro.server because thats the lambda thats invoking the remotion
lambda.

**Comment by karelnagel** [comment]
It worked using only `permission` instead of `transform.server.permissions` so I used that. 

There is still issues with the bucket/role/policy naming so I had to change the bucket name for now so it would work for me, but this is just a temporary workaround.

I will merge this and start solving the naming issues on a separate branch. Thank you!

**Comment by ryanleecode** [comment]
~~@karelnagel the problem with that is if you do any linking it will overwrite the linked permissions. so you need to use transform to merge them.~~

NVM thats wrong

**Comment by ryanleecode** [comment]
@karelnagel i checked the IAM roles and if its just permissions, they don't get inlined without using transform

**Comment by karelnagel** [comment]
hmm, I'm not sure now, is using the permissions instead of transforms ok or not? 😀

Ideally I think the best way would be to use SST linking https://ion.sst.dev/docs/linking/ to attach permissions, fn names, sites etc instead of adding all of these one by one.

**Comment by ryanleecode** [comment]
> hmm, I'm not sure now, is using the permissions instead of transforms ok or not? 😀
> 
> Ideally I think the best way would be to use SST linking https://ion.sst.dev/docs/linking/ to attach permissions, fn names, sites etc instead of adding all of these one by one.

Im working in next rn so maybe its different in astro but if i create a bucket or database and link it with the next app, but i also set the permissions field. the linked permissions will get overwritten. hence you need to merge them in transform.

**Comment by karelnagel** [comment]
well thats interesting, but if we use `link:[remotion]` as well then it shouldn't be an issue right?

I sort of got linking working in here https://github.com/karelnagel/pulumi-remotion-lambda/pull/8, but the Link import comes from  .sst folder so it won't work as a package as it is.

**Pull request merged**
